# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    param_fetcher_listener:  true
    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
        formats: { json: true, xml: false, rss: false }
        mime_types:
            json: ['application/json', 'application/ld+json', 'application/json;version=1.0', 'application/json;version=2.0']
    exception:
        enabled: true
        codes:
           App\Exception\ResourceValidationException: 400

    format_listener:
        rules:
           - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, xml ] }
        #    - { path: ^/user, prefer_extension: true, fallback_format: json, priorities: [ json, xml ] }
        #    - { path: ^/login_check, prefer_extension: true, fallback_format: json, priorities: [ json, xml ] }
    serializer:
        serialize_null: true
    versioning:
        enabled: true
        resolvers:
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'        

