nelmio_api_doc:
    documentation:
        info:
            title: Ametcity API
            description: This is an awesome app!
            version: 1.0.0
    # areas: # to filter documented areas
    #     default:
    #         path_patterns: [ /api/noRoute/ ]
        # path_patterns:
        #     - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        # host_patterns:
        #     - ^api\.
