#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\UserController\AuthController::register
    methods: POST

login_check:
    path:     /login_check
    methods:  [POST]

rest_controller:
    resource: ../src/Controller/
    type: annotation
    prefix: /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
# app.swagger:
#     path: /api/doc.json
#     methods: GET
#     defaults: { _controller: nelmio_api_doc.controller.swagger }